set_property PACKAGE_PIN Y9 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
create_clock -period 10.000 -name clk -waveform {0.000 5.000} [get_ports clk]

set_property PACKAGE_PIN P16 [get_ports button_in]
set_property IOSTANDARD LVCMOS33 [get_ports button_in]

set_property PACKAGE_PIN V10 [get_ports rx_in]
set_property IOSTANDARD LVCMOS33 [get_ports rx_in]

set_property PACKAGE_PIN W11 [get_ports tx_out]
set_property IOSTANDARD LVCMOS33 [get_ports tx_out]

set_property PACKAGE_PIN T22 [get_ports {led[0]}]
set_property PACKAGE_PIN T21 [get_ports {led[1]}]
set_property PACKAGE_PIN U22 [get_ports {led[2]}]
set_property PACKAGE_PIN U21 [get_ports {led[3]}]
set_property PACKAGE_PIN V22 [get_ports {led[4]}]
set_property PACKAGE_PIN W22 [get_ports {led[5]}]
set_property PACKAGE_PIN U19 [get_ports {led[6]}]
set_property PACKAGE_PIN U14 [get_ports {led[7]}]



#set_property PACKAGE_PIN F22 [get_ports {data_i[0]}]
#set_property PACKAGE_PIN G22 [get_ports {data_i[1]}]
#set_property PACKAGE_PIN H22 [get_ports {data_i[2]}]
#set_property PACKAGE_PIN F21 [get_ports {data_i[3]}]
#set_property PACKAGE_PIN H19 [get_ports {data_i[4]}]
#set_property PACKAGE_PIN H18 [get_ports {data_i[5]}]
#set_property PACKAGE_PIN H17 [get_ports {data_i[6]}]
#set_property PACKAGE_PIN M15 [get_ports {data_i[7]}]
#
#set_property IOSTANDARD LVCMOS33 [get_ports {data_i[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_i[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_i[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_i[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_i[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_i[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_i[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {data_i[7]}]

set_property IOSTANDARD LVCMOS33 [get_ports {led[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {led[7]}]
